server:
  port: 8765
spring:
  application:
    name: config-server
  profiles:
    active: native, #spring.profiles.active# # 配置使用本地储存
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

